config/routes.rb
Rails.application.routes.draw do

  get 'howtouse/index'
  # root
  root to: 'tops#index'

  # resources化
  resources :likes, only: [:show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # sessionsコントローラー
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # statisticsコントローラー
  get '/statistics', to: 'statistics#index'

  # ゲストログイン用
  post '/tops/guest_sign_in', to: 'sessions#new_guest'

  # howtouse用
  get '/howtouse', to: 'howtouse#index'

  resources :posts
  resources :users do
    member do
      get :followings, :followers
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index
    @genres_list = ["音楽", "アニメ", "ゲーム", "お笑い", "キッズ", "いやし", "美容", "料理", "勉強", "趣味", "ビジネス", "ニュース", "すべて"]
  end

end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/index.html.slim
.row.align-items-center.justify-content-center
  .toppage-eyecatch
    .eyecatch-phrase
      h4 ジャンル別YouTube発掘サイト
    .eyecatch-guestloginbutton
      div = link_to "ゲストログイン", tops_guest_sign_in_path, method: :post, class: "btn btn-success"
    .eyecatch-postbutton
      - if current_user
        div = link_to "投稿", new_post_path, class: "btn btn-primary"
    .eyecatch-postbutton
      - if current_user
        div = link_to "使用方法", howtouse_path, class: "btn btn-secondary"
.row
  - @genres_list.each do |one_genre|
    .col-6.col-sm-6.col-md-4.col-lg-3.text-center
      = link_to one_genre, posts_path(post_genre: one_genre), class: "btn btn-primary btn-lg toppage-genrebuttons"