config/routes.rb
Rails.application.routes.draw do

  get 'howtouse/index'
  # root
  root to: 'tops#index'

  # resources化
  resources :likes, only: [:show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # sessionsコントローラー
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # statisticsコントローラー
  get '/statistics', to: 'statistics#index'

  # ゲストログイン用
  post '/tops/guest_sign_in', to: 'sessions#new_guest'

  # howtouse用
  get '/howtouse', to: 'howtouse#index'

  resources :posts
  resources :users do
    member do
      get :followings, :followers
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  counter_culture :post
  
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :good_users, through: :likes, source: :user
  
  validates :comment, presence: true, length: { maximum: 30 }
    VALID_YOUTUBE_URL = /\Ahttps:\/\/(www\.youtube\.com\/watch\?v=|m\.youtube\.com\/watch\?v=|youtu\.be\/)[-\w]{11}\z/
  validates :youtube_url, format: { with: VALID_YOUTUBE_URL, message: "が誤っています"}
  validates :genre, presence: { message: "を指定してください" }

  def good?(user)
    good_users.include?(user)
  end

  def good(user)
    likes.create(user_id: user.id)
  end

  def ungood(user)
    likes.find_by(user_id: user.id).destroy
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :image, ImageUploader

  attr_accessor :remember_token

  has_many :posts, foreign_key: :user_id, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user, dependent: :destroy

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 10 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 64 },
    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

    has_secure_password
  validates :password, presence: true, length: { in: 6..64 }
  validates :sex, presence: :true
  validates :age, presence: :true

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.create(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.guest
    find_or_create_by!(name: "ゲストユーザー", sex: "フリー", age:"26~30才", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/howtouse_controller.rb
class HowtouseController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def show
    @user = User.find(params[:id])
    @likes = @user.likes.all
  end

  def create
    @post = Post.find(params[:post_id])
    unless @post.good?(current_user)
      @post.good(current_user)
      @post.reload
      respond_to do |format|
        format.html { redirect_to request.referrer || root_url }
        format.js
      end
    end
  end

  def destroy
    @post = Like.find(params[:id]).post
    if @post.good?(current_user)
      @post.ungood(current_user)
      @post.reload
      respond_to do |format|
        format.html { redirect_to request.referrer || root_url }
        format.js
      end
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :destroy]

  def index
    if params[:post_genre]  == "すべて"
      @posts = Post.all.order(created_at: :desc)
    else
      @posts = Post.where(genre: params[:post_genre]).order(created_at: :desc)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    check_youtubeurl @post.youtube_url
    if @post.save
      redirect_to @post.user, notice: "投稿できました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @post.update!(post_params)
    redirect_to @post.user, notice: "編集できました"
  end

  def destroy
    if @post.destroy
      redirect_to current_user, notice: "削除に成功しました"
    else
      redirect_to current_user, alert: "削除できませんでした"
    end
  end

  def find_post
    @post = Post.find(params[:id])
  end

  private
    def post_params
      params.require(:post).permit(:comment, :youtube_url, :genre)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to root_path, notice: 'ログインしました'
    else
      flash.now[:danger] = 'Eメールアドレスまたはパスワードが誤っています'
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path, notice: 'ログアウトしました'
  end

  def new_guest
    user = User.guest
    log_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました"
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index
    @genres_list = ["音楽", "アニメ", "ゲーム", "お笑い", "キッズ", "いやし", "美容", "料理", "勉強", "趣味", "ビジネス", "ニュース", "すべて"]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :followings, :followers, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "会員登録が完了しました"
      redirect_to @user
    else
      render :new
      @user = User.new(user_params)
    end
  end

  def show
    @posts = @user.posts.order(created_at: :desc)
  end

  def destroy
    @user.destroy
    flash[:success] = "退会に成功しました"
    redirect_to root_path
  end

  def followings
    @users = @user.followings
    render 'show_followings'
  end

  def followers
    @users = @user.followers
    render 'show_followers'
  end

  private
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:image, :name, :sex, :age, :email, :password, :password_confirmation, :image_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/howtouse_helper.rb
module HowtouseHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Tube
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet"
    meta content="width=device-width, initial-scale=1" name="viewport" /
  body
    .header
      nav.navbar.navbar-expand-sm.navbar-light
        = link_to root_path
          #logo = image_tag "App-Logo.png", size: "102x38"
        button.navbar-toggler aria-controls="navbar-id" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbar-id" data-toggle="collapse" type="button" 
          span.navbar-toggler-icon
        #navbar-id.collapse.navbar-collapse.justify-content-end
          ul.navbar-nav
            - if current_user
              li.nav-item
                a.nav-link href="/posts/new" 投稿する
              li.nav-item
                a.nav-link href="/posts?post_genre=すべて" 投稿を見る
              li.nav-item
                a.nav-link href="/users" 全ユーザー
              li.nav-item
                a.nav-link href="/statistics" 統計情報
              li.dropdown
                a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
                  = image_tag current_user.image.thumb50.url, size: "35x35"
                  = current_user.name
                ul.dropdown-menu.pull-right
                  li = link_to "マイページ", current_user, class: 'nav-link'
                  li = link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link', data: { confirm: 'ログアウトしますか？' }
            - else
              li.nav-item
                a.nav-link href="/login" ログイン
              li.nav-item
                a.nav-link href="/users/new" 会員登録
    .wrapper
      .container
        - flash.each do |message_type, message|
          div class="alert alert-#{message_type}" = message
        = yield
    .footer
      .text-center.text-muted ©Tube 2020

app/views/shared/_post_card.html.slim
.col-12.col-sm-12.col-md-6.col-lg-4
  .card.border-primary.mb-3
    .card-header.bg-transparent
      .post-header-top
        .post-header-left
        = link_to post.user do
          = image_tag post.user.image.thumb50.url
          = post.user.name
        .post-header-right
          .post-time
            = time_ago_in_words(post.created_at)
          .post-genre 
            = link_to posts_path(post_genre: post.genre) do
              = post.genre
          .post-good
          - if post.user == current_user
            div  = link_to "編集", edit_post_path(post), class: "btn btn-success"
            div  = link_to "削除", post_path(post), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger"
          - else
            div data-post-id="#{post.id}" id="post-#{post.id}" 
              = render "likes/like", post: post
      .post-header-bottom
        .post-comment 
          = post.comment
    
    .post-body.embed-responsive.embed-responsive-16by9
      iframe src="https://www.youtube.com/embed/#{post.youtube_url.last(11)}"
    

app/views/shared/_post_form.html.slim
.col-md-4
  .card.text-black.border-primary.mb-3 style=("max-width: 20rem;") 
    .card-header.bg-transparent.border-primary
      = link_to post.user do
        = image_tag post.user.image.thumb50.url
        = post.user.name
    iframe src="https://www.youtube.com/embed/#{post.youtube_url.last(11)}"
    .card-body
      h5.card-title= post.comment
    ul.list-group.list-group-flush
      li.list-group-item.border-primary
        = link_to posts_path(post_genre: post.genre) do
          = post.genre
      li.list-group-item.border-primary
        = l post.created_at
    div data-post-id="#{post.id}" id="post-#{post.id}" 
      = render "likes/like", post: post

app/views/shared/_user_header.html.slim
h3
  = image_tag @user.image.thumb50.url
  | #{title}
h5
  | 投稿数：#{@user.posts.count}件
  - if current_user == @user
  div = link_to "退会", user_path(current_user), method: :delete, data: {confirm: "ユーザーを削除しますか？"}, class: "btn btn-danger"

  - if current_user && @user != current_user
    #follow_form
      - if current_user.following?(@user)
        = render "users/unfollow"
      - else
        = render "users/follow"
      

.row
  .col-3
    = link_to "いいね:#{@user.likes.count}", like_path
  .col-3
    = link_to "フォロー:#{@user.followings.count}", followings_user_path(@user.id)
  .col-3
    = link_to "フォロワー:#{@user.followers.count}", followers_user_path(@user.id)

app/views/shared/_user_table.html.slim
table.table.table-hover
  thead
    tr
      th #{title}
      th 投稿数
      th いいね獲得数
    - @users.each do |user|
      tbody
        tr
          td
            = link_to user do 
              = image_tag user.image.thumb50.url
              = user.name
          td
            = user.posts.count
          td
            = user.likes.count